- name: Waiting for SSH connection
  ansible.builtin.wait_for_connection:

- name: Gathering facts
  ansible.builtin.setup:

- name: Cloning CyberPot install directory
  ansible.builtin.git:
    repo: "https://github.com/khulnasoft/cyberpot.git"
    dest: /root/cyberpot

- name: Prepare to set user password
  ansible.builtin.set_fact:
    user_name: "{{ ansible_user }}"
    user_salt: "s0mew1ck3dTpoT"
  no_log: true

- name: Changing password for user {{ user_name }}
  ansible.builtin.user:
   name: "{{ ansible_user }}"
   password: "{{ user_password | password_hash('sha512', user_salt) }}"
   state: present
   shell: /bin/bash

- name: Copy CyberPot configuration file
  ansible.builtin.copy:
    src: ../../../../../../iso/installer/cyberpot.conf.dist
    dest: /root/cyberpot.conf
    owner: root
    group: root
    mode: 0644

- name: Install CyberPot on instance -  be patient, this might take 15 to 30 minutes depending on the connection speed.
  ansible.builtin.command: /root/cyberpot/iso/installer/install.sh --type=auto --conf=/root/cyberpot.conf

- name: Delete CyberPot configuration file
  ansible.builtin.file:
    path: /root/cyberpot.conf
    state: absent

- name: Change unattended-upgrades to take default action
  ansible.builtin.blockinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    block: |
      Dpkg::Options {
        "--force-confdef";
        "--force-confold";
      }
