- name: Generate CyberPot name
  ansible.builtin.set_fact:
    cyberpot_name: "cyberpot-ansible-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=6') }}"

- name: Create instance {{ ansible_loop.index }} of {{ ansible_loop.length }}
  openstack.cloud.server:
    cloud: "{{ cloud }}"
    name: "{{ cyberpot_name }}"
    availability_zone: "{{ availability_zone }}"
    image: "{{ image }}"
    boot_from_volume: yes
    volume_size: "{{ volume_size }}"
    key_name: "{{ key_name }}"
    auto_ip: yes
    flavor: "{{ flavor }}"
    security_groups: sg-cyberpot-ansible
    network: network-cyberpot-ansible
  register: cyberpot

- name: Add instance to inventory
  ansible.builtin.add_host:
    hostname: "{{ cyberpot_name }}"
    ansible_host: "{{ cyberpot.server.public_v4 }}"
    groups: cyberpot
