# CyberPot Image Builder (use only for building docker images)
version: '2.3'

services:

##################
#### Honeypots
##################

# Adbhoney service
  adbhoney:
    build: adbhoney/.
    image: "khulnasoft/adbhoney:2204"

# Ciscoasa service
  ciscoasa:
    build: ciscoasa/.
    image: "khulnasoft/ciscoasa:2204"

# CitrixHoneypot service
  citrixhoneypot:
    build: citrixhoneypot/.
    image: "khulnasoft/citrixhoneypot:2204"

# Conpot IEC104 service
  conpot_IEC104:
    build: conpot/.
    image: "khulnasoft/conpot:2204"

# Cowrie service
  cowrie:
    build: cowrie/.
    image: "khulnasoft/cowrie:2204"

# Ddospot service
  ddospot:
    build: ddospot/.
    image: "khulnasoft/ddospot:2204"

# Dicompot service
  dicompot:
    build: dicompot/.
    image: "khulnasoft/dicompot:2204"

# Dionaea service
  dionaea:
    build: dionaea/.
    image: "khulnasoft/dionaea:2204"

# ElasticPot service
  elasticpot:
    build: elasticpot/.
    image: "khulnasoft/elasticpot:2204"

# Endlessh service
  endlessh:
    build: endlessh/.
    image: "khulnasoft/endlessh:2204"

# Glutton service
  glutton:
    build: glutton/.
    image: "khulnasoft/glutton:2204"

# Hellpot service
  hellpot:
    build: hellpot/.
    image: "khulnasoft/hellpot:2204"

# Heralding service
  heralding:
    build: heralding/.
    image: "khulnasoft/heralding:2204"

# Honeypots service
  honeypots:
    build: honeypots/.
    image: "khulnasoft/honeypots:2204"

# Honeytrap service
  honeytrap:
    build: honeytrap/.
    image: "khulnasoft/honeytrap:2204"

# IPPHoney service
  ipphoney:
    build: ipphoney/.
    image: "khulnasoft/ipphoney:2204"

# Log4Pot service
  log4pot:
    build: log4pot/.
    image: "khulnasoft/log4pot:2204"

# Mailoney service
  mailoney:
    build: mailoney/.
    image: "khulnasoft/mailoney:2204"

# Medpot service
  medpot:
    build: medpot/.
    image: "khulnasoft/medpot:2204"

# Redishoneypot service
  redishoneypot:
    build: redishoneypot/.
    image: "khulnasoft/redishoneypot:2204"

# Sentrypeer service
  sentrypeer:
    build: sentrypeer/.
    image: "khulnasoft/sentrypeer:2204"

#### Snare / Tanner
## Tanner Redis Service
  tanner_redis:
    build: tanner/redis/.
    image: "khulnasoft/redis:2204"

## PHP Sandbox service
  tanner_phpox:
    build: tanner/phpox/.
    image: "khulnasoft/phpox:2204"

## Tanner API Service
  tanner_api:
    build: tanner/tanner/.
    image: "khulnasoft/tanner:2204"

## Snare Service
  snare:
    build: tanner/snare/.
    image: "khulnasoft/snare:2204"


##################
#### NSM
##################

# Fatt service
  fatt:
    build: fatt/.
    image: "khulnasoft/fatt:2204"

# P0f service
  p0f:
    build: p0f/.
    image: "khulnasoft/p0f:2204"

# Suricata service
  suricata:
    build: suricata/.
    image: "khulnasoft/suricata:2204"


##################
#### Tools
##################

#### ELK
## Elasticsearch service
  elasticsearch:
    build: elk/elasticsearch/.
    image: "khulnasoft/elasticsearch:2204"

## Kibana service
  kibana:
    build: elk/kibana/.
    image: "khulnasoft/kibana:2204"

## Logstash service
  logstash:
    build: elk/logstash/.
    image: "khulnasoft/logstash:2204"

# Ewsposter service
  ewsposter:
    build: ewsposter/.
    image: "khulnasoft/ewsposter:2204"

# Nginx service
  nginx:
    build: nginx/.
    image: "khulnasoft/nginx:2204"

# Spiderfoot service
  spiderfoot:
    build: spiderfoot/.
    image: "khulnasoft/spiderfoot:2204"

# Map Web Service
  map_web:
    build: elk/map/.
    image: "khulnasoft/map:2204"
